config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :bills do 
  get "invoice", on: :member
end

get "billing" => "bills#index"

app/models/bill.rb
class Bill < ActiveRecord::Base
  unloadable


  belongs_to :project
  has_many :billed_issues
  has_many :issues, through: :billed_issues

  accepts_nested_attributes_for :billed_issues
end

app/models/billed_issue.rb
class BilledIssue < ActiveRecord::Base
  unloadable

  belongs_to :issue
  belongs_to :bill
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  unloadable

  def index
    @bills = Bill.order(created_at: :desc)
  end

  def new
    @issues = Issue.where(id: params[:ids])
    @bill = Bill.new
    @bill.issues = @issues 
  end

  def create
    @bill = Bill.new(bill_params)
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def invoice
    @bill = Bill.find(params[:id])
    render layout: false
  end

  private
  
  def bill_params
    params.require(:bill).permit(billed_issues_attributes: [:issue_id, :rate, :quantity, :tax, :sum])
  end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= @bill.issues.first.project.identifier %>

<table>
  <th>
    <td>#</td>
    <td><%= l :billed_issues_subject %></td>
    <td><%= l :billed_issues_rate %></td>
    <td><%= l :billed_issues_quantity %></td>
    <td><%= l :billed_issues_units %></td>
    <td><%= l :billed_issues_tax %></td>
    <td><%= l :billed_issues_sum %></td>
  </th>
  <%= f.fields_for :billed_issues do |billed_issue_f| %>
    <% @bill.issues.each do |issue| %>
      <tr>
        <td><%= billed_issue_f.hidden_field :issue_id, value: issue.id %><%=issue.id%></td>
        <td><%= billed_issue_f.text_field :subject, value: issue.subject %></td>
        <td><%= billed_issue_f.text_field :rate %></td>
        <td><%= billed_issue_f.text_field :quantity %></td>
        <td><%= billed_issue_f.text_field :units %></td>
        <td><%= billed_issue_f.text_field :tax %></td>
        <td><%= billed_issue_f.text_field :sum %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/bills/index.html.erb
<h2><%= l(:label_billing) %></h2>
<p class="subtitle">здесь подзаголовок</p>

<div >
  <table>
    <tr>
      <th><%= l(:bill_id)%></th>
      <th><%= l(:bill_status)%></th>
      <th><%= l(:bill_total_sum)%></th>
      <th><%= l(:bill_created_at)%></th>
      <th><%= l(:bill_updated_at)%></th>
    </tr>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.id %></td>
        <td><%= bill.status %></td>
        <td><%= bill.total_sum %></td>
        <td><%= bill.created_at %></td>
        <td><%= bill.updated_at %></td>
      </tr>
    <% end %>
  </table>
</div>


<% content_for :sidebar do %>
  <div>Placeholder for sidebar</div>
<% end %>

<% html_title(l(:label_billing), @author) -%>

app/views/bills/new.html.erb
<%= title l(:label_bill_new) %>

<%= form_for @bill do |f| %>
  <%= error_messages_for 'bill' %>
  <div class="box tabular">
    <div id="all_attributes">
    <%= render :partial => 'bills/form', :locals => {:f => f} %>
    </div>
  </div>

  <%= submit_tag l(:button_create) %>
<% end %>

app/views/issues/_new_bill_context_menu.erb
<li><%= context_menu_link l(:create_bill), new_bill_path(:ids => @issue_ids)%></li>

app/views/settings/_project_settings.erb
<h1>TEST</h1>